In [ ]:
pip install nltk spacy scikit-learn


In [ ]:
import spacy

# Download the model
!python -m spacy download en_core_web_sm

# Load the model
nlp = spacy.load('en_core_web_sm')

# Example usage
doc = nlp("This is a sentence.")
for token in doc:
    print(token.text, token.lemma_, token.pos_, token.dep_)


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 32.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
This this PRON nsubj
is be AUX ROOT
a a DET det
sentence sentence NOUN attr
. . PUNCT punct


In [ ]:
# Whitespace Tokenization
def whitespace_tokenize(text):
    return text.split()

# Example usage
text = "This is an example sentence."
tokens = whitespace_tokenize(text)
print("Whitespace Tokenization:", tokens)

Whitespace Tokenization: ['This', 'is', 'an', 'example', 'sentence.']


In [ ]:
from collections import defaultdict

# Function to get the frequency of pairs
def get_stats(vocab):
    pairs = defaultdict(int)
    for word, freq in vocab.items():
        symbols = word.split()
        for i in range(len(symbols) - 1):
            pairs[(symbols[i], symbols[i + 1])] += freq
    return pairs

# Function to merge the most frequent pair
def merge_vocab(pair, vocab):
    bigram = ' '.join(pair)
    new_vocab = {}
    for word in vocab:
        new_word = word.replace(bigram, ''.join(pair))
        new_vocab[new_word] = vocab[word]
    return new_vocab

# Initial vocabulary with frequencies
vocab = {
    'b a n a n a': 1,
    'b a n a n a s': 1,
    'b a n': 2,
}

# Number of merges to perform
num_merges = 2

for i in range(num_merges):
    pairs = get_stats(vocab)
    if not pairs:
        break
    best = max(pairs, key=pairs.get)
    vocab = merge_vocab(best, vocab)
    print(f"Merge {i + 1}: {best}")
    print(f"Updated Vocab: {vocab}")

# Final tokens
final_tokens = list(vocab.keys())
print(f"Final Tokens: {final_tokens}")

Merge 1: ('a', 'n')
Updated Vocab: {'b an an a': 1, 'b an an a s': 1, 'b an': 2}
Merge 2: ('b', 'an')
Updated Vocab: {'ban an a': 1, 'ban an a s': 1, 'ban': 2}
Final Tokens: ['ban an a', 'ban an a s', 'ban']


In [ ]:
def lowercase(text):
    return text.lower()

text = "This is an Example Sentence."
lowercased_text = lowercase(text)
print("Lowercased:", lowercased_text)

Lowercased: this is an example sentence.


In [ ]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

words = ["running", "ran", "easily", "fairly"]
lemmas = [lemmatizer.lemmatize(word, pos='v') for word in words]
print("Lemmatized Words:", lemmas)

[nltk_data] Downloading package wordnet to /root/nltk_data...


Lemmatized Words: ['run', 'run', 'easily', 'fairly']


In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

# Download necessary NLTK data
nltk.download('punkt')

# Initialize the stemmer
stemmer = PorterStemmer()

# Sample text
text = "running runs runner ran easily fairly"

# Tokenize the text
words = word_tokenize(text)

# Apply stemming
stemmed_words = [stemmer.stem(word) for word in words]
print("Original Words:", words)
print("Stemmed Words:", stemmed_words)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Original Words: ['running', 'runs', 'runner', 'ran', 'easily', 'fairly']
Stemmed Words: ['run', 'run', 'runner', 'ran', 'easili', 'fairli']


In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt')

stop_words = set(stopwords.words('english'))
text = "This is a sample sentence, showing off the stop words filtration."
words = word_tokenize(text)
filtered_words = [word for word in words if word.lower() not in stop_words]

print("Filtered Words:", filtered_words)

Filtered Words: ['sample', 'sentence', ',', 'showing', 'stop', 'words', 'filtration', '.']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger')

sentence = "The quick brown fox jumps over the lazy dog."
words = nltk.word_tokenize(sentence)

# POS Tagging
pos_tags = nltk.pos_tag(words)
print("POS Tags:", pos_tags)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


POS Tags: [('The', 'DT'), ('quick', 'JJ'), ('brown', 'NN'), ('fox', 'NN'), ('jumps', 'VBZ'), ('over', 'IN'), ('the', 'DT'), ('lazy', 'JJ'), ('dog', 'NN'), ('.', '.')]


In [ ]:
pip install hmmlearn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 kB 3.1 MB/s eta 0:00:00


In [ ]:
import numpy as np
from hmmlearn import hmm


model = hmm.GaussianHMM(n_components=2, covariance_type="diag")

# Example data
X = np.array([[0.1], [0.5], [0.8], [1.2], [1.6], [2.0]])
lengths = [6]

# Fit model
model.fit(X, lengths)

# Predict hidden states
hidden_states = model.predict(X)
print("Hidden states:", hidden_states)

Hidden states: [0 0 0 1 1 1]


In [ ]:
import spacy

# Load SpaCy English model
nlp = spacy.load("en_core_web_sm")

text = "Apple is looking at buying U.K. startup for $1 billion."

# Process the text
doc = nlp(text)

# Extract named entities
for entity in doc.ents:
    print(f"Entity: {entity.text}, Label: {entity.label_}")

Entity: Apple, Label: ORG
Entity: U.K., Label: GPE
Entity: $1 billion, Label: MONEY


In [ ]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')

text = "I love this product! It's amazing and wonderful."

# Initialize sentiment analyzer
sid = SentimentIntensityAnalyzer()

# Analyze sentiment
scores = sid.polarity_scores(text)
print("Sentiment Scores:", scores)

Sentiment Scores: {'neg': 0.0, 'neu': 0.25, 'pos': 0.75, 'compound': 0.9184}


[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("Vocabulary:", vectorizer.vocabulary_)
print("Bag of Words Representation:\n", X.toarray())

Vocabulary: {'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}
Bag of Words Representation:
 [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
